### ISSUE TITLE
Is this the proper way to clean up after a job?

### ISSUE THREAD

**Issue by naps62** [naps62/imageflow_ex#1]
[relevant code here](https://github.com/naps62/imageflow_ex/blob/2aa109f8396c0864fdc0760189b8c764e274f4ea/native/imageflow_ex/src/job.rs#L97-L103)

I took inspiration for this from the imageflow-node bindings. My understanding is that calling `Box::into_raw` when creating a job "leaks" that memory so that it doesn't get destroyed when the function is finished (which in this case, means control is going back to Elixir), and calling `Box::from_raw` reverts that process and allows Rust to destroy that object once this function finish

I traced this by adding a `println!()` statement at `impl Drop for Context` in the imageflow package. That is indeed called in the right place, but I'm not 100% sure about this solution

**Comment by naps62** [comment]
cc/ @lilith

**Comment by lilith** [comment]
That is correct. You can see the imageflow_abi equivalent here: https://github.com/imazen/imageflow/blob/b86389026f84565c17c0f4d4e03e12c83cfd2619/imageflow_abi/src/lib.rs#L300-L306
