### ISSUE TITLE
Error handling needs work

### ISSUE THREAD

**Issue by lilith** [naps62/imageflow_ex#3]
Imageflow works hard to minimize `panics`, which end the process unless handled. Some panics, such as OOM, can't be avoided and must be caught to prevent process termination. 

1. Creating the context can be done without panicking, using `Context::create_cant_panic()` https://github.com/imazen/imageflow/blob/b86389026f84565c17c0f4d4e03e12c83cfd2619/imageflow_abi/src/lib.rs#L280

2. When performing operations on a context, you should check to see if the context is in an error state and handle it appropriately with `Context.outward_error().has_error()` I use a [macro](https://github.com/imazen/imageflow/blob/b86389026f84565c17c0f4d4e03e12c83cfd2619/imageflow_abi/src/lib.rs#L204-L225) for this in imageflow_abi. Contexts in general shouldn't be used after an error, as it could be from a panic which left the context in an inconsistent state. 

3. When calling ctx.message() you should wrap it in a `catch_unwind(AssertUnwindSafe(|| {` method as [done here](https://github.com/imazen/imageflow/blob/b86389026f84565c17c0f4d4e03e12c83cfd2619/imageflow_abi/src/lib.rs#L554-L581) Same for [.add_input_buffer](https://github.com/imazen/imageflow/blob/b86389026f84565c17c0f4d4e03e12c83cfd2619/imageflow_abi/src/lib.rs#L695-L707), .add_output_buffer, etc.

**Comment by naps62** [comment]
Thank you. I'll look into these tomorrow

**Comment by naps62** [comment]
@lilith Fixed this in the latest commit. feel free to take a look and let me know if I messed up somewhere 😛
