### ISSUE TITLE
get_output_buffer will crash if provided an non-existent io_id

### ISSUE THREAD

**Issue by lilith** [naps62/imageflow_ex#4]
Due to unwrap here https://github.com/naps62/imageflow_ex/blob/2aa109f8396c0864fdc0760189b8c764e274f4ea/native/imageflow_ex/src/job.rs#L59

**Comment by naps62** [comment]
https://github.com/naps62/imageflow_ex/commit/ff1a323cefe3f1828587183baac37024fe9850e6 also fixes this

The Job API now returns a consistent error tuple in the event of any error such as this:

![image](https://user-images.githubusercontent.com/283819/102220596-f0dff800-3ed8-11eb-8734-dbee11a7f3ea.png)
