### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gushonorato** [naps62/imageflow_ex#6]
I've installed Rust 1.2 using asdf and tried to compile the package inside a Phoenix 1.5 app, but I got the following error:

```
thread '<main>' panicked at 'invalid serialized PackageId', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/option.rs:330
```

Can you help me?

**Comment by gushonorato** [comment]
I'm using macOSX Catalina 10.15.7

**Comment by gushonorato** [comment]
I tried with version 1.54 and it worked! Sorry, I'm totally newbie in Rust 😄

**Comment by naps62** [comment]
yep, rust 1.2 is pretty old, so I'm guessing it's not supported :)
